data:
  requests_cpu: "0.1"
  requests_memory: "640M"
  limits_cpu: "1"
  limits_memory: "1G"
  serviceAccountName: ""
  imagePullPolicy: "IfNotPresent"
  image: ""
  cloud_sql_proxy_version: "1.20.0"
  sql_connection_string: ""

conf:
  configmap: "entitlements-config"
  app_name: "entitlements"
  secret_name: "entitlements-secret"
