data:
  # common
  requests_cpu: "0.1"
  requests_memory: "640M"
  limits_cpu: "1"
  limits_memory: "1G"
  serviceAccountName: "entitlements"
  image: ""
  imagePullPolicy: "IfNotPresent"
  # gcp
  cloud_sql_proxy_version: "1.20.0"
  sql_connection_string: ""
  # bootstrap common
  bootstrap_limits_cpu: "0.1"
  bootstrap_limits_memory: "200M"
  bootstrap_image: ""
  bootstrapServiceAccountName: ""
conf:
  configmap: "entitlements-config"
  app_name: "entitlements"
  entitlements_postgres_secret_name: "entitlements-postgres-secret"
  # bootstrap onprem
  bootstrap_openid_secret_name: "datafier-secret"
  on_prem_enabled: false
auth:
  public_url: ""
  local_url: "keycloak"
  realm: "osdu"
