data:
  # Configmaps
  dataPartitionId: ""
  dataPartitionIdList: []
  entitlementsHost: "http://entitlements"
  adminUserEmail: ""
  airflowComposerEmail: ""
  logLevel: "ERROR"
  openidProviderClientIds: ""
  partitionApi: "http://partition/api/partition/v1/"
  googleAudiences: ""
  springProfilesActive: "gcp"
  projectId: ""
  pubSubEmail: ""
  registerPubsubIdentity: ""
  partitionAuthEnabled: false
  # redis connection
  redisEntHost: "redis-ent-master"
  redisEntPort: 6379
  # Don't change or use the parameter unless necessary
  entitlementsDomain: "group"
  # Deployments
  bootstrapImage: ""
  bootstrapServiceAccountName: ""
  requestsCpu: "0.1"
  requestsMemory: "640M"
  limitsCpu: "1"
  limitsMemory: "1G"
  serviceAccountName: "entitlements"
  image: ""
  imagePullPolicy: "IfNotPresent"
  cloudSqlProxyVersion: "1.32.0"
  sqlConnectionString: ""
conf:
  configmap: "entitlements-config"
  appName: "entitlements"
  entitlementsPostgresSecretName: "entitlements-postgres-secret"
  bootstrapOpenidSecretName: "datafier-secret"
  onPremEnabled: false
  istioEnabled: true
auth:
  publicUrl: ""
  localUrl: "keycloak"
  realm: "osdu"
istio:
  proxyCPU: "50m"
  proxyCPULimit: "500m"
  proxyMemory: "64Mi"
  proxyMemoryLimit: "512Mi"
  bootstrapProxyCPU: "10m"
  bootstrapProxyCPULimit: "100m"
