variables:
  BUILD_BOOTSTRAP_PATH: "provider/entitlements-v2-jdbc/bootstrap/Dockerfile"
  BUILD_PATH: "provider/entitlements-v2-jdbc/cloudbuild/Dockerfile.cloudbuild"
  OSDU_GCP_ENABLE_BOOTSTRAP: "true"
  OSDU_GCP_SERVICE: entitlements
  OSDU_GCP_TEST_SUBDIR: "testing/$OSDU_GCP_SERVICE-v2-test-$OSDU_GCP_VENDOR"
  OSDU_GCP_TEST_PROJECT: "$OSDU_GCP_SERVICE-v2-test-core,$OSDU_GCP_SERVICE-v2-test-$OSDU_GCP_VENDOR"
  OSDU_GCP_VENDOR: jdbc

osdu-gcp-anthos-test:
  variables:
    OSDU_GCP_VENDOR: anthos
