variables:
  AZURE_SERVICE: entitlements-v2
  AZURE_BUILD_SUBDIR: provider/entitlements-v2-azure
  AZURE_TEST_SUBDIR: testing/entitlements-v2-test-azure

  AWS_BUILD_SUBDIR: provider/entitlements-v2-aws/build-aws
  AWS_TEST_SUBDIR: testing/entitlements-v2-test-aws
  AWS_SERVICE: entitlements-v2
  AWS_ENVIRONMENT: dev
  AWS_DEPLOY_TARGET: EKS
  AWS_EKS_DEPLOYMENT_NAME: os-entitlements

  IBM_BUILD_SUBDIR: provider/entitlements-v2-ibm
  IBM_INT_TEST_SUBDIR: testing/entitlements-v2-test-ibm

include:
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "build/maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/fossa-maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/gitlab-ultimate.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/azure.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-global.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "publishing/pages.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/ibm.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/osdu-gcp-gke.yml"

  - local: "devops/gcp/pipeline/override-stages.yml"
