variables:
  AZURE_SERVICE: entitlements-v2
  AZURE_BUILD_SUBDIR: provider/entitlements-v2-azure
  AZURE_TEST_SUBDIR: testing/entitlements-v2-test-azure

  AWS_BUILD_SUBDIR: provider/entitlements-v2-aws/build-aws
  AWS_TEST_SUBDIR: testing/entitlements-v2-test-aws
  AWS_SERVICE: entitlements-v2
  AWS_ENVIRONMENT: dev
  AWS_DEPLOY_TARGET: EKS
  AWS_EKS_DEPLOYMENT_NAME: os-entitlements

  IBM_BUILD_SUBDIR: provider/entitlements-v2-ibm
  IBM_INT_TEST_SUBDIR: testing/entitlements-v2-test-ibm

  OSDU_GCP_SERVICE: entitlements-v2
  OSDU_GCP_VENDOR: jdbc
  OSDU_GCP_HELM_NAMESPACE: default
  OSDU_GCP_HELM_CONFIG_SERVICE_VARS: "--set data.domain=$DOMAIN --set data.google_audiences=$GOOGLE_AUDIENCE --set data.openid_provider_client_ids=$GOOGLE_AUDIENCE --set data.partition_api=$OSDU_GCP_PARTITION_API"
  OSDU_GCP_HELM_CONFIG_SERVICE_VARS_DEV2: "--set data.domain=$DOMAIN --set data.google_audiences=$GOOGLE_AUDIENCE --set data.openid_provider_client_ids=$GOOGLE_AUDIENCE --set data.partition_api=$OSDU_GCP_PARTITION_API"
  OSDU_GCP_HELM_DEPLOYMENT_SERVICE_VARS: "--set data.image=$CI_REGISTRY_IMAGE/osdu-gcp:$CI_COMMIT_SHORT_SHA --set data.serviceAccountName=$OSDU_GCP_SERVICE-k8s --set data.sql_connection_string=$OSDU_GCP_SQL_CONNECTION_STRING"
  OSDU_GCP_HELM_CONFIG_SERVICE: entitlements-config
  OSDU_GCP_HELM_DEPLOYMENT_SERVICE: entitlements-deploy
  OSDU_GCP_HELM_PACKAGE_CHARTS: "devops/gcp/deploy devops/gcp/configmap"

include:
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "build/maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/fossa-maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/gitlab-ultimate.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/azure.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-global.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "publishing/pages.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/ibm.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/osdu-gcp-gke.yml"

osdu-gcp-deploy-deployment:
  variables:
    OSDU_GCP_SERVICE: entitlements

osdu-gcp-dev2-deploy-deployment:
  variables:
    OSDU_GCP_SERVICE: entitlements

osdu-gcp-dev2-deploy-configmap:
  variables:
    OSDU_GCP_SERVICE: entitlements

osdu-gcp-helm-charts-master:
  variables:
    OSDU_GCP_HELM_BOOTSTRAP_DIR: "devops/gcp/bootstrap"
  script:
    - helm cm-push $OSDU_GCP_HELM_CONFIG_DIR ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/stable --username gitlab-ci-token --password $CI_JOB_TOKEN
    - helm cm-push $OSDU_GCP_HELM_DEPLOYMENT_DIR ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/stable --username gitlab-ci-token --password $CI_JOB_TOKEN
    - helm cm-push $OSDU_GCP_HELM_BOOTSTRAP_DIR ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/stable --username gitlab-ci-token --password $CI_JOB_TOKEN

