variables:
  AZURE_SERVICE: entitlements-v2
  AZURE_BUILD_SUBDIR: provider/entitlements-v2-azure
  AZURE_TEST_SUBDIR: testing/entitlements-v2-test-azure

  AWS_BUILD_SUBDIR: provider/entitlements-v2-aws/build-aws
  AWS_TEST_SUBDIR: testing/entitlements-v2-test-aws
  AWS_SERVICE: entitlements-v2
  AWS_ENVIRONMENT: dev
  AWS_DEPLOY_TARGET: EKS
  AWS_EKS_DEPLOYMENT_NAME: os-entitlements

  IBM_BUILD_SUBDIR: provider/entitlements-v2-ibm
  IBM_INT_TEST_SUBDIR: testing/entitlements-v2-test-ibm

  OSDU_GCP_ENABLE_BOOTSTRAP: "true"
  OSDU_GCP_SERVICE: entitlements-v2
  OSDU_GCP_VENDOR: jdbc
  OSDU_GCP_HELM_NAMESPACE: default
  OSDU_GCP_HELM_CONFIG_SERVICE_VARS: > 
    --set data.domain=$DOMAIN
    --set data.google_audiences=$GOOGLE_AUDIENCE
    --set data.openid_provider_client_ids=$GOOGLE_AUDIENCE
    --set data.partition_api=$OSDU_GCP_PARTITION_API
    --set data.data_partition_id=$OSDU_GCP_TENANT
    --set data.project_id=$OSDU_GCP_PROJECT
    --set data.airflow_composer_email=$OSDU_GCP_AIRFLOW_COMPOSER_EMAIL
    --set data.admin_user_email=$OSDU_GCP_ADMIN_USER_EMAIL
    --set data.pub_sub_email=$OSDU_GCP_PUB_SUB_EMAIL
    --set data.register_pubsub_identity=$OSDU_GCP_REGISTER_PUBSUB_IDENTITY
  OSDU_GCP_HELM_CONFIG_SERVICE_VARS_DEV2: >
    --set data.domain=$DOMAIN
    --set data.google_audiences=$GOOGLE_AUDIENCE
    --set data.openid_provider_client_ids=$GOOGLE_AUDIENCE
    --set data.partition_api=$OSDU_GCP_PARTITION_API
    --set data.data_partition_id=$OSDU_GCP_TENANT
    --set data.project_id=$OSDU_GCP_PROJECT
    --set data.airflow_composer_email=$OSDU_GCP_AIRFLOW_COMPOSER_EMAIL
    --set data.admin_user_email=$OSDU_GCP_ADMIN_USER_EMAIL
    --set data.pub_sub_email=$OSDU_GCP_PUB_SUB_EMAIL
    --set data.register_pubsub_identity=$OSDU_GCP_REGISTER_PUBSUB_IDENTITY
  OSDU_GCP_HELM_DEPLOYMENT_SERVICE_VARS: >
    --set data.bootstrapServiceAccountName=$OSDU_GCP_BOOTSTRAP_SERVICE_ACCOUNT
    --set data.image=$CI_REGISTRY_IMAGE/osdu-gcp-entitlements:$CI_COMMIT_SHORT_SHA
    --set data.bootstrap_image=$CI_REGISTRY_IMAGE/osdu-gcp-bootstrap-entitlements:$CI_COMMIT_SHORT_SHA
    --set data.serviceAccountName=$OSDU_GCP_SERVICE-k8s
    --set data.sql_connection_string=$OSDU_GCP_SQL_CONNECTION_STRING
  # FIXME add value below to DEV2 pipeline
  OSDU_GCP_HELM_DEPLOYMENT_SERVICE_VARS_DEV2: >
    --set data.bootstrapServiceAccountName=$OSDU_GCP_BOOTSTRAP_SERVICE_ACCOUNT
    --set data.bootstrap_image=$CI_REGISTRY_IMAGE/osdu-gcp-bootstrap-entitlements:${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}
  OSDU_GCP_HELM_CONFIG_SERVICE: entitlements-config
  OSDU_GCP_HELM_DEPLOYMENT_SERVICE: entitlements-deploy
  OSDU_GCP_HELM_PACKAGE_CHARTS: "devops/gcp/deploy devops/gcp/configmap"

include:
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "build/maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/fossa-maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/gitlab-ultimate.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/azure.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-global.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "publishing/pages.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/ibm.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/osdu-gcp-gke.yml"

osdu-gcp-containerize-gitlab:
  variables:
    IMAGE_NAME: osdu-gcp-entitlements

osdu-gcp-containerize-gcr:
  variables:
    IMAGE_NAME: osdu-gcp-entitlements

osdu-gcp-containerize-bootstrap-gitlab:
  variables:
    IMAGE_NAME: osdu-gcp-bootstrap-entitlements

osdu-gcp-containerize-bootstrap-gcr:
  variables:
    IMAGE_NAME: osdu-gcp-bootstrap-entitlements

osdu-gcp-deploy-deployment:
  variables:
    OSDU_GCP_SERVICE: entitlements
    OSDU_GCP_BOOTSTRAP_SERVICE: "entitlements-bootstrap"
    OSDU_GCP_BOOTSTRAP_SERVICE_ACCOUNT: "datafier-workload-identity-gke"
  needs: ["osdu-gcp-containerize-gitlab", "osdu-gcp-containerize-bootstrap-gitlab", "osdu-gcp-deploy-configmap"]
  after_script:
     - echo ----- Verify Bootstrap -----
     - kubectl rollout status deployment.v1.apps/$OSDU_GCP_BOOTSTRAP_SERVICE -n $OSDU_GCP_HELM_NAMESPACE --timeout=900s
     - POD=$(kubectl get pod --sort-by=.metadata.creationTimestamp -n $OSDU_GCP_HELM_NAMESPACE | grep $OSDU_GCP_BOOTSTRAP_SERVICE | tail -1 | awk '{print $1}')
     - STATUS=$(kubectl wait -n $OSDU_GCP_HELM_NAMESPACE --for=condition=Ready pod/$POD --timeout=300s)
     - echo $STATUS
     - if [[ "$STATUS" != *"met"* ]]; then echo "POD didn't start correctly" ; exit 1 ; fi

osdu-gcp-deploy-configmap:
  variables:
    OSDU_GCP_SERVICE: entitlements
    # FIXME check if it possible to move variables to ci-cd pipelines repo
    OSDU_GCP_ADMIN_USER_EMAIL: datafier@nice-etching-277309.iam.gserviceaccount.com
    OSDU_GCP_AIRFLOW_COMPOSER_EMAIL: osdu-community-sa-airflow@nice-etching-277309.iam.gserviceaccount.com
    OSDU_GCP_PUB_SUB_EMAIL: pub-sub-indexer-queue@nice-etching-277309.iam.gserviceaccount.com
    OSDU_GCP_REGISTER_PUBSUB_IDENTITY: register-pubsub-identity@nice-etching-277309.iam.gserviceaccount.com

osdu-gcp-dev2-deploy-deployment:
  variables:
    OSDU_GCP_SERVICE: entitlements
    OSDU_GCP_BOOTSTRAP_SERVICE: entitlements-bootstrap
    OSDU_GCP_BOOTSTRAP_SERVICE_ACCOUNT: workload-gke-bootstrap-sa
  # FIXME check if it possible to move variables to ci-cd pipelines repo, comment strings below if something is wrong with dev2 pipeline    
  needs: ["osdu-gcp-containerize-gitlab", "osdu-gcp-containerize-bootstrap-gitlab", "osdu-gcp-dev2-deploy-configmap"]
  after_script:
     - echo ----- Verify Bootstrap -----
     - kubectl rollout status deployment.v1.apps/$OSDU_GCP_BOOTSTRAP_SERVICE -n $OSDU_GCP_HELM_NAMESPACE --timeout=900s
     - POD=$(kubectl get pod --sort-by=.metadata.creationTimestamp -n $OSDU_GCP_HELM_NAMESPACE | grep $OSDU_GCP_BOOTSTRAP_SERVICE | tail -1 | awk '{print $1}')
     - STATUS=$(kubectl wait -n $OSDU_GCP_HELM_NAMESPACE --for=condition=Ready pod/$POD --timeout=300s)
     - echo $STATUS
     - if [[ "$STATUS" != *"met"* ]]; then echo "POD didn't start correctly" ; exit 1 ; fi

osdu-gcp-dev2-deploy-configmap:
  variables:
    OSDU_GCP_SERVICE: entitlements
    # FIXME check if it possible to move variables to ci-cd pipelines repo
    OSDU_GCP_ADMIN_USER_EMAIL: datafier@osdu-dev2.iam.gserviceaccount.com
    OSDU_GCP_AIRFLOW_COMPOSER_EMAIL: osdu-sa-airflow-composer@osdu-dev2.iam.gserviceaccount.com
    OSDU_GCP_PUB_SUB_EMAIL: pub-sub-indexer-queue@osdu-dev2.iam.gserviceaccount.com
    OSDU_GCP_REGISTER_PUBSUB_IDENTITY: register-pubsub-identity@osdu-dev2.iam.gserviceaccount.com
    OSDU_GCP_BOOTSTRAP_NAMESPACE: config
    OSDU_GCP_ENTITLEMENTS_HOST: http://entitlements.$OSDU_GCP_HELM_NAMESPACE.svc.cluster
