variables:
  AZURE_SERVICE: entitlements-v2
  AZURE_BUILD_SUBDIR: provider/entitlements-v2-azure
  AZURE_TEST_SUBDIR: testing/entitlements-v2-test-azure

  AWS_BUILD_SUBDIR: provider/entitlements-v2-aws/build-aws
  AWS_TEST_SUBDIR: testing/entitlements-v2-test-aws
  AWS_CHART_SUBDIR: devops/aws/chart
  AWS_SERVICE: entitlements-v2
  AWS_SERVICE_GATEWAY: osdu-gateway
  AWS_ENVIRONMENT: dev
  AWS_DEPLOY_TARGET: TF
  AWS_EKS_DEPLOYMENT_NAME: os-entitlements

  IBM_BUILD_SUBDIR: provider/entitlements-v2-ibm
  IBM_INT_TEST_SUBDIR: testing/entitlements-v2-test-ibm
  IBM_HELM_CONFIG_PATH: devops/ibm/ibm-entitlement-config
  IBM_HELM_DEPLOY_PATH: devops/ibm/ibm-entitlement-deploy
  IBM_HELM_BOOTSTRAP_PATH: devops/ibm/ibm-entitlement-registration

include:
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "build/maven.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/fossa-maven.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/gitlab-ultimate.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/azure.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-global.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-maven.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "publishing/pages.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/ibm.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/gc-global.yml"
    ref: m18-pipeline-update-mm

  - local: "devops/gc/pipeline/override-stages.yml"
