data:
  # Configmaps
  dataPartitionId: ""
  dataPartitionIdList: []
  entitlementsHost: "http://entitlements"
  adminUserEmail: ""
  airflowComposerEmail: ""
  logLevel: "ERROR"
  partitionHost: "http://partition"
  springProfilesActive: "gcp"
  projectId: ""
  pubSubEmail: ""
  registerPubsubIdentity: ""
  # redis connection. Change it if you want to use external redis
  redisEntHost: ""
  redisEntPort: 6379
  redisImage: "docker.io/library/redis:7"
  # Don't change or use the parameter unless necessary
  entitlementsDomain: "group"
  # Deployments
  bootstrapImage: ""
  bootstrapServiceAccountName: ""
  requestsCpu: "75m"
  requestsMemory: "640M"
  limitsCpu: "1"
  limitsMemory: "1G"
  serviceAccountName: "entitlements"
  image: ""
  imagePullPolicy: "IfNotPresent"
  cloudSqlProxyVersion: "1.32.0"
  sqlConnectionString: ""
conf:
  configmap: "entitlements-config"
  appName: "entitlements"
  entitlementsPostgresSecretName: "entitlements-postgres-secret"
  bootstrapOpenidSecretName: "datafier-secret"
  onPremEnabled: false
  istioEnabled: true
  entitlementsRedisSecretName: "entitlements-redis-secret"
auth:
  publicUrl: ""
  localUrl: "keycloak"
  realm: "osdu"
istio:
  proxyCPU: "25m"
  proxyCPULimit: "200m"
  proxyMemory: "64Mi"
  proxyMemoryLimit: "512Mi"
  bootstrapProxyCPU: "10m"
  bootstrapProxyCPULimit: "100m"
  sidecarInject: true
