apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.conf.configmap }}"
data:
  LOG_LEVEL: "{{ .Values.data.logLevel }}"
  JAVA_APP_JAR: "{{ .Values.data.javaAppJar }}"
  server.port: "{{ .Values.data.serverPort }}"
  spring.main.allow-bean-definition-overriding: "{{ .Values.data.beanDefOverriding }}"
  ACCEPT_HTTP: "{{ .Values.data.acceptHttp }}"
  LOG_PREFIX: "{{ .Values.data.logPrefix }}"
  VM_CACHE_EXPIRATION: "{{ .Values.data.cacheExpiration }}"
  MAX_CACHE_VALUE_SIZE: "{{ .Values.data.cahceMaxSize }}"
  ibm.health-check-uri: "{{ .Values.data.healthCheckUri }}"
  logging.level.org.springframework.web: "{{ .Values.data.loggingLevelSpring }}"
  DEPLOYMENT_ENVIRONMENT: "{{ .Values.data.deployEnv }}"
  ibm.env.prefix: "{{ .Values.data.envPrefix }}"
  ibm.env.prefix_project: "{{ .Values.data.envPrefixProject }}"
  PARTITION_API: "http://{{ .Release.Name }}-ibm-partition-deploy:8080/api/partition/v1"
  partition.keycloak.client_id: "{{ .Values.data.pKCClientId }}"
  partition.keycloak.client_secert: "{{ .Values.data.pKCClientSecret }}"
  partition.keycloak.grant_type: "{{ .Values.data.grantType }}"
  partition.keycloak.password: "{{ .Values.data.pKCPassword }}"
  partition.keycloak.realm: "{{ .Values.data.keycloakRealm }}"
  partition.keycloak.url: "{{ .Values.data.pKCEndPointHost }}"
  partition.keycloak.user: "{{ .Values.data.pKCUser }}"
  partition.keycloak.accept_http: "{{ .Values.data.pKAcceptHttp }}"
  tenantCache.exp.time.in.second: "{{ .Values.data.tenantCacheExpiryInSec }}"
  redis-host: "{{ .Release.Name }}-redis-master"
  redishost: "{{ .Release.Name }}-redis-master"
  rediskey: referenv
  redisport: "{{ .Values.data.redisport }}"