apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.conf.appName | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ .Values.conf.appName | quote }}
    type: core
    source: java
spec:
  replicas: {{ .Values.conf.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.conf.appName | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.conf.appName | quote }}
        sidecar.istio.io/inject: {{ .Values.istio.sidecarInject | quote }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        sidecar.istio.io/proxyCPU: {{ .Values.istio.proxyCPU | quote }}
        sidecar.istio.io/proxyMemory: {{ .Values.istio.proxyMemory | quote }}
        sidecar.istio.io/proxyCPULimit: {{ .Values.istio.proxyCPULimit | quote }}
        sidecar.istio.io/proxyMemoryLimit: {{ .Values.istio.proxyMemoryLimit | quote }}
    spec:
      containers:
      - image: {{ .Values.data.image | quote }}
        imagePullPolicy: {{ .Values.data.imagePullPolicy | quote }}
        name: {{ .Values.conf.appName | quote }}
        envFrom:
        - configMapRef:
            name: {{ .Values.conf.configmap | quote }}
        - secretRef:
            name: {{ .Values.conf.entitlementsPostgresSecretName | quote }}
        env:
        - name: REDIS_USER_GROUPS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.conf.entitlementsRedisSecretName | quote }}
              key: REDIS_PASSWORD
        - name: REDIS_USER_INFO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.conf.entitlementsRedisSecretName | quote }}
              key: REDIS_PASSWORD
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 10001
        resources:
          requests:
            cpu: {{ .Values.data.requestsCpu | quote }}
            memory: {{ .Values.data.requestsMemory | quote }}
          {{- if .Values.global.limitsEnabled }}
          limits:
            cpu: {{ .Values.data.limitsCpu | quote }}
            memory: {{ .Values.data.limitsMemory | quote }}
          {{- end }}
      {{- if not .Values.global.onPremEnabled }}
      - image: "gcr.io/cloudsql-docker/gce-proxy:{{ .Values.data.cloudSqlProxyVersion }}"
        imagePullPolicy: {{ .Values.data.imagePullPolicy | quote }}
        name: cloud-sql-proxy
        command:
          - /cloud_sql_proxy
          - "-instances={{ .Values.data.sqlConnectionString }}=tcp:5432"
      {{- end }}
        ports:
        - containerPort: 8080
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/liveness
            port: 8081
          initialDelaySeconds: 150
          periodSeconds: 10
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/readiness
            port: 8081
          periodSeconds: 10
      serviceAccountName: {{ .Values.data.serviceAccountName | quote }}
