{{- if .Values.conf.istioEnabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.conf.appName | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  hosts:
    {{- if .Values.auth.publicUrl }}
    - {{ printf "osdu.%s" .Values.auth.publicUrl | quote }}
    {{- else }}
    - "*"
    {{- end }}
  gateways:
    - service-gateway
  http:
    - match:
        - uri:
            prefix: "/api/entitlements/v2"
      route:
        - destination:
            port:
              number: 80
            host: {{ printf "%s.%s.svc.cluster.local" .Values.conf.appName .Release.Namespace | quote }}
{{- end }}
