#  Copyright © Microsoft Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: osdu
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        aadpodidbinding: osdu-identity
    spec:
      volumes:
        - name: azure-keyvault
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-keyvault
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}/{{ .Chart.Name }}-{{ .Values.image.branch }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: {{ .Values.server.servlet.contextPath }}/_ah/readiness_check
              port: 80
          volumeMounts:
            - name: azure-keyvault
              mountPath: '/mnt/azure-keyvault'
              readOnly: true
          env:
            - name: LOGGING_LEVEL
              value: INFO
            - name: server.port
              value: '80'
            - name: KEYVAULT_URI
              valueFrom:
                configMapKeyRef:
                  name: osdu-svc-properties
                  key: ENV_KEYVAULT
            - name: aad_client_id
              valueFrom:
                secretKeyRef:
                  name: active-directory
                  key: application-appid
            - name: appinsights_key
              valueFrom:
                secretKeyRef:
                  name: central-logging
                  key: appinsights
            - name: partition_service_endpoint
              value: http://partition/api/partition/v1
            - name: GREMLIN_ENDPOINT
              value: {{ .Values.app.gremlin.endpoint }}
            - name: GREMLIN_USERNAME
              value: {{ .Values.app.gremlin.username }}
            - name: cosmosdb_database
              value: osdu-db
            - name: COSMOS_DB_ACCOUNT_NAME
              value: {{ .Values.app.cosmosdb.cosmosDbAccountName }}
            - name: AZURE_RESOURCE_GROUP
              value: {{ .Values.app.cosmosdb.resourceGroup }}
            - name: AZURE_SUBSCRIPTION_ID
              value: {{ .Values.app.cosmosdb.subscriptionId }}
            - name: INTEGRATION_TESTER
              value: {{ .Values.app.integration.tester}}
            - name: azure_istioauth_enabled
              value: "true"