---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "entitlements-registration.fullname" . }}
  labels:
    {{- include "entitlements-registration.labels" . | nindent 4 }}
data:
  entitlements_post.sh: |
    {{- tpl (.Files.Get "files/entitlements_post.sh" ) . | nindent 4 }}
