{{- if .Values.conf.onPremEnabled }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: "{{ .Values.conf.appName }}-jwt-policy"
  namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.conf.appName }}"
  action: ALLOW
  rules:
  - from:
    - source:
       requestPrincipals: ["*"]
    when:
    - key: request.auth.claims[iss]
      values:
      - "https://keycloak.{{- default (printf "%s.%s" ((index (lookup "v1" "Service" .Values.auth.istioNamespace "istio-ingressgateway").status.loadBalancer.ingress 0).ip) "nip.io") .Values.auth.publicUrl -}}/auth/realms/{{ .Values.auth.realm }}"
      - "http://keycloak.{{- default (printf "%s.%s" ((index (lookup "v1" "Service" .Values.auth.istioNamespace "istio-ingressgateway").status.loadBalancer.ingress 0).ip) "nip.io") .Values.auth.publicUrl -}}/auth/realms/{{ .Values.auth.realm }}"
      - "http://{{ .Values.auth.localUrl }}/auth/realms/{{ .Values.auth.realm }}"
{{- end }}
