{{- if .Values.conf.on_prem_enabled }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: "{{ .Values.conf.app_name }}-jwt-policy"
  namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.conf.app_name }}"
  action: ALLOW
  rules:
  - from:
    - source:
       requestPrincipals: ["*"]
    when:
    - key: request.auth.claims[iss]
      values:
      - "{{ .Values.auth.public_url }}/auth/realms/{{ .Values.auth.realm }}"
      - "{{ .Values.auth.local_url }}/auth/realms/{{ .Values.auth.realm }}"
{{- end }}
