{{- if .Values.conf.onPremEnabled }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: "{{ .Values.conf.appName }}-jwt-policy"
  namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.conf.appName }}"
  action: ALLOW
  rules:
  - from:
    - source:
       requestPrincipals: ["*"]
    when:
    - key: request.auth.claims[iss]
      values:
      - "https://keycloak.{{ .Values.auth.publicUrl }}/realms/{{ .Values.auth.realm }}"
      - "http://keycloak.{{ .Values.auth.publicUrl }}/realms/{{ .Values.auth.realm }}"
      - "http://{{ .Values.auth.localUrl }}/realms/{{ .Values.auth.realm }}"
{{- end }}
