apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.conf.app_name }}"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    rollme: {{ randAlphaNum 5 | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.conf.app_name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.conf.app_name }}"
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
      - image: "{{ .Values.data.image }}"
        imagePullPolicy: "{{ .Values.data.imagePullPolicy }}"
        name: "{{ .Values.conf.app_name }}"
        envFrom:
        - configMapRef:
            name: "{{ .Values.conf.configmap }}"
        - secretRef:
            name: "{{ .Values.conf.entitlements_postgres_secret_name }}"
      {{- if not .Values.conf.on_prem_enabled }}
      - image: "gcr.io/cloudsql-docker/gce-proxy:{{ .Values.data.cloud_sql_proxy_version }}"
        imagePullPolicy: "{{ .Values.data.imagePullPolicy }}"
        name: cloud-sql-proxy
        command:
          - /cloud_sql_proxy
          - "-instances={{ .Values.data.sql_connection_string }}=tcp:5432"
      {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "{{ .Values.data.requests_cpu }}"
            memory: "{{ .Values.data.requests_memory }}"
          limits:
            cpu: "{{ .Values.data.limits_cpu }}"
            memory: "{{ .Values.data.limits_memory }}"
      serviceAccountName: "{{ .Values.data.serviceAccountName }}"
