{{- if .Values.conf.on_prem_enabled }}
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: "{{ .Values.conf.app_name }}-jwt-policy"
  namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.conf.app_name }}"
  jwtRules:
  - issuer: "{{ .Values.auth.public_url }}/auth/realms/{{ .Values.auth.realm }}"
    jwksUri: "{{ .Values.auth.local_url }}.{{ .Release.Namespace }}.svc.cluster.local/auth/realms/{{ .Values.auth.realm }}/protocol/openid-connect/certs"
    forwardOriginalToken: true
  - issuer: "{{ .Values.auth.local_url }}/auth/realms/{{ .Values.auth.realm }}"
    jwksUri: "{{ .Values.auth.local_url }}.{{ .Release.Namespace }}.svc.cluster.local/auth/realms/{{ .Values.auth.realm }}/protocol/openid-connect/certs"
    forwardOriginalToken: true
{{- end }}
