apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.conf.appName }}"
  namespace: "{{ .Release.Namespace }}"
  {{- if not .Values.conf.onPremEnabled }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  {{- end }}
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: "{{ .Values.conf.appName }}"
