apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ .Values.conf.app_name }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  hosts:
    {{- if .Values.auth.public_url }}
    - {{ printf "osdu.%s" .Values.auth.public_url | quote }}
    {{- else }}
    - "*"
    {{- end }}
  gateways:
    - service-gateway
  http:
    - match:
        - uri:
            prefix: "/api/entitlements/v2"
      route:
        - destination:
            port:
              number: 80
            host: "{{ .Values.conf.app_name }}.{{ .Release.Namespace }}.svc.cluster.local"
