apiVersion: v1
kind: Secret
metadata:
  labels:
    app: "{{ .Values.conf.app_name }}"
  name: "{{ .Values.conf.secret_name }}"
  namespace: "{{ .Release.Namespace }}"
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: "{{ .Values.data.spring_datasource_password }}"
